# Generated by Django 4.1.7 on 2023-02-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_immatriculation', models.CharField(max_length=20)),
                ('nombre_place', models.IntegerField()),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicule.modele', verbose_name='modele')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('annee_experience', models.IntegerField()),
                ('numero_permis', models.CharField(max_length=50)),
                ('type_permis', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C')], default=1, max_length=5)),
                ('groupe_sanguin', models.CharField(choices=[('1', 'A+'), ('2', 'B+'), ('3', '0+')], default=1, max_length=5)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicule.vehicule', verbose_name='marque')),
            ],
        ),
    ]
