# Generated by Django 4.1.7 on 2023-02-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_representant_alter_modele_modele_producteur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='producteur',
        ),
        migrations.DeleteModel(
            name='Representant',
        ),
    ]
