# Generated by Django 4.1.7 on 2023-03-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent',
            table='Agent',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
    ]
