# Generated by Django 4.1.7 on 2023-03-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_alter_agent_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_image',
            field=models.ImageField(null=True, upload_to='Property'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_picture',
            field=models.ImageField(null=True, upload_to='Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to='Property'),
        ),
    ]
