# Generated by Django 4.1.7 on 2023-03-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0004_alter_agent_agent_image_alter_city_city_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
