# Generated by Django 4.1.7 on 2023-03-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_delete_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(null=True)),
                ('Property_type', models.CharField(choices=[('S', 'sale'), ('R', 'rent')], max_length=100)),
                ('area', models.DecimalField(decimal_places=10, max_digits=40)),
                ('beds_number', models.PositiveIntegerField(null=True)),
                ('baths_number', models.PositiveIntegerField(null=True)),
                ('garages_number', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Property')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Property.category', verbose_name='Category')),
            ],
            options={
                'db_table': 'property',
            },
        ),
    ]
