# Generated by Django 4.1.7 on 2023-03-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0007_alter_property_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Citiers'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_image',
            field=models.ImageField(null=True, upload_to='Agent'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_picture',
            field=models.ImageField(null=True, upload_to='City'),
        ),
        migrations.AlterModelTable(
            name='agent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='property',
            table=None,
        ),
    ]
