# Generated by Django 4.1.7 on 2023-03-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0008_alter_agent_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterModelTable(
            name='property',
            table='Property',
        ),
    ]
