# Generated by Django 4.1.7 on 2023-03-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0009_alter_property_options_alter_property_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelTable(
            name='property',
            table=None,
        ),
    ]
