# Generated by Django 4.1.7 on 2023-03-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0010_alter_property_options_alter_property_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
