# Generated by Django 4.1.7 on 2023-03-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0011_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
