# Generated by Django 4.1.7 on 2023-03-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0012_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
    ]
