# Generated by Django 4.1.7 on 2023-02-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classe', verbose_name='classe'),
        ),
    ]
