# Generated by Django 4.1.7 on 2023-03-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testform', '0002_student_age_student_contact_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=150)),
                ('econtact', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
