# Generated by Django 4.1.7 on 2023-02-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producteur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='representant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producteur.representant', verbose_name='representant'),
        ),
    ]
